name: "[Internal use] Continuous integration for project validation"
on:
  push:
    branches:
      - "rubric*"
      - main

jobs:
  ci:
    if: github.repository_owner == 'betrybe'
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022
        python-version:
          - "3.11.1"
          - "3.10"
          - "3.9"
          - "3.8"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v3

      - name: Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python version
        run: python --version

      - name: Install project requirements
        run: "pip install -r dev-requirements.txt"

      - name: Run linter
        run: flake8
        continue-on-error: true

      - name: Run tests
        run: pytest
